/**
 * Generate the CRM database schema, runtime model, and TypeScript types from Bullhorn's
 * entity metadata. Deterministic: same metadata in, same files out. Output is committed
 * as a numbered migration — this script never touches a live database.
 *
 *   node crm/scripts/gen-schema.js
 *     → crm/db/migrations/0001_init.sql
 *     → crm/model/entities.json       (labels, types, options, required, links — used at runtime)
 *     → crm/src/generated/entities.ts (strict types per entity)
 */
const fs = require("fs"), path = require("path");
const ROOT = path.join(__dirname, "..");
const META = path.join(ROOT, "..", "docs", "bullhorn-model", "all-entities");

const ENTITIES = ["CorporateUser", "Department", "Country", "State", "Category", "Specialty", "BusinessSector", "Skill", "Certification", "CandidateSource", "Location", "TimeUnit", "WorkersCompensationRate", "HousingComplex",
  "ClientCorporation", "ClientContact", "Candidate", "Lead", "Opportunity", "JobOrder", "JobSubmission", "JobSubmissionHistory", "Placement", "PlacementChangeRequest", "PlacementCommission",
  "Note", "NoteEntity", "Task", "Appointment", "AppointmentAttendee", "Sendout", "Tearsheet", "TearsheetMember",
  "CandidateEducation", "CandidateWorkHistory", "CandidateReference", "CandidateCertification", "JobBoardPost"];
const TABLE = {}; ENTITIES.forEach(e => TABLE[e] = snake(e));
const SKIP_FIELDS = new Set(["_score", "migrateGUID", "estaffGUID", "bteSyncStatus", "lastBteSyncDate", "payrollSyncStatus", "payrollEmployeeType", "onboardingReceivedSent", "loginRestrictions", "userHousingComplexUnits", "housingAmenities", "clientCorporationBlob", "externalMobileDevices"]);
const SKIP_TO_MANY_TARGETS = /FileAttachment$|EditHistory$|TrustData$|CustomObjectInstance|ReferenceResponse$|TimeAndExpense|ScreenerQuestion|CertificationRequirement|Versions?$|Gis$|Amenity$|HousingComplexUnit$|Shift$|TearsheetRecipient$/;

function snake(s) { return s.replace(/([a-z0-9])([A-Z])/g, "$1_$2").replace(/([A-Z]+)([A-Z][a-z])/g, "$1_$2").toLowerCase(); }
function sqlType(f) {
  const d = f.dataType, s = f.dataSpecialization;
  if (d === "Integer") return "integer";
  if (d === "BigDecimal") return s === "MONEY" ? "numeric(14,2)" : "numeric";
  if (d === "Double") return s === "MONEY" ? "numeric(14,2)" : (s === "PERCENTAGE" ? "numeric(8,4)" : "double precision");
  if (d === "Boolean") return "boolean";
  if (d === "Timestamp") return s === "DATE" ? "date" : "timestamptz";
  if (d === "Date") return "date";
  if (d === "String") return f.maxLength && f.maxLength < 10000 ? "varchar(" + f.maxLength + ")" : "text";
  if (d === "byte[]") return "bytea";
  return "text";
}
function tsType(f) {
  const d = f.dataType;
  if (["Integer", "BigDecimal", "Double"].includes(d)) return "number";
  if (d === "Boolean") return "boolean";
  return "string";
}

const model = {}, sql = [], ts = [], joins = [], allFks = [];
sql.push("-- 0001_init.sql — generated by crm/scripts/gen-schema.js from Bullhorn metadata. Do not edit by hand; regenerate and add a new migration.");
sql.push("CREATE SCHEMA IF NOT EXISTS crm;");
sql.push("CREATE TABLE IF NOT EXISTS crm.audit_log (id BIGSERIAL PRIMARY KEY, at TIMESTAMPTZ NOT NULL DEFAULT now(), actor_id INTEGER, actor_name TEXT, entity TEXT NOT NULL, entity_id INTEGER NOT NULL, action TEXT NOT NULL, transaction_id UUID NOT NULL, field TEXT, old_value JSONB, new_value JSONB, source TEXT NOT NULL DEFAULT 'crm');");
sql.push("CREATE INDEX IF NOT EXISTS audit_log_entity ON crm.audit_log (entity, entity_id, at DESC);");
sql.push("CREATE TABLE IF NOT EXISTS crm.idempotency (key TEXT PRIMARY KEY, actor_id INTEGER, response JSONB NOT NULL, at TIMESTAMPTZ NOT NULL DEFAULT now());");
for (const e of ENTITIES) {
  const m = JSON.parse(fs.readFileSync(path.join(META, e + ".json"), "utf8"));
  const t = TABLE[e];
  const cols = ["  id integer PRIMARY KEY"], fks = [], mfields = [], tsf = [];
  for (const f of m.fields || []) {
    if (f.name === "id" || SKIP_FIELDS.has(f.name) || f.name.startsWith("_")) continue;
    const base = { name: f.name, column: null, label: f.label || f.name, type: f.type, dataType: f.dataType || null, spec: f.dataSpecialization || null, required: !!f.required, readonly: !!f.readonly, maxLength: f.maxLength || null, options: f.options ? f.options.map(o => ({ value: o.value, label: o.label })) : null, optionsType: f.optionsType || null, inputType: f.inputType || null, multiValue: !!f.multiValue, link: null };
    if (f.type === "SCALAR") {
      const c = snake(f.name); base.column = c;
      cols.push("  " + c + " " + (f.multiValue ? "text[]" : sqlType(f)));
      tsf.push("  " + f.name + "?: " + tsType(f) + (f.multiValue ? "[]" : "") + " | null;");
    } else if (f.type === "COMPOSITE" && /Address/.test(f.dataType)) {
      base.column = snake(f.name) + "_*";
      for (const sub of ["address1", "address2", "city", "state", "zip", "countryID", "countryName", "timezone"]) cols.push("  " + snake(f.name) + "_" + snake(sub) + (sub === "countryID" ? " integer" : " text"));
      tsf.push("  " + f.name + "?: { address1?: string; address2?: string; city?: string; state?: string; zip?: string; countryID?: number; countryName?: string } | null;");
    } else if (f.type === "TO_ONE") {
      const target = f.associatedEntity && f.associatedEntity.entity; const c = snake(f.name) + "_id"; base.column = c; base.link = target || null;
      cols.push("  " + c + " integer");
      if (target && TABLE[target]) fks.push("ALTER TABLE crm." + t + " ADD CONSTRAINT fk_" + t + "_" + c + " FOREIGN KEY (" + c + ") REFERENCES crm." + TABLE[target] + "(id) DEFERRABLE INITIALLY DEFERRED;");
      tsf.push("  " + f.name + "?: { id: number } | null;");
    } else if (f.type === "TO_MANY") {
      const target = f.associatedEntity && f.associatedEntity.entity; base.link = target || null;
      if (!(target && TABLE[target] && !SKIP_TO_MANY_TARGETS.test(target))) continue;
      const jt = t + "__" + snake(f.name);
      const tc = TABLE[target] === t ? "related_" + TABLE[target] + "_id" : TABLE[target] + "_id";
      joins.push("CREATE TABLE IF NOT EXISTS crm." + jt + " (" + t + "_id integer NOT NULL REFERENCES crm." + t + "(id) ON DELETE CASCADE, " + tc + " integer NOT NULL REFERENCES crm." + TABLE[target] + "(id) DEFERRABLE INITIALLY DEFERRED, PRIMARY KEY (" + t + "_id, " + tc + "));");
      base.joinColumn = tc;
      base.joinTable = jt;
      tsf.push("  " + f.name + "?: { id: number }[] | null;");
    } else continue;
    mfields.push(base);
  }
  cols.push("  created_at timestamptz NOT NULL DEFAULT now()", "  updated_at timestamptz NOT NULL DEFAULT now()", "  deleted_at timestamptz", "  created_by integer", "  updated_by integer", "  row_version integer NOT NULL DEFAULT 1", "  bh_synced_at timestamptz");
  sql.push("CREATE TABLE IF NOT EXISTS crm." + t + " (\n" + cols.join(",\n") + "\n);");
  sql.push("CREATE INDEX IF NOT EXISTS " + t + "_updated ON crm." + t + " (updated_at DESC);");
  allFks.push.apply(allFks, fks);
  model[e] = { table: t, label: m.label || e, fields: mfields };
  ts.push("export interface " + e + " {\n  id: number;\n" + tsf.join("\n") + "\n}");
}
sql.push("-- foreign keys, after every table exists");
sql.push.apply(sql, allFks);
sql.push.apply(sql, joins);
sql.push("-- new records get ids above anything Bullhorn ever issued");
for (const e of ENTITIES) sql.push("CREATE SEQUENCE IF NOT EXISTS crm." + TABLE[e] + "_id_seq START 10000000;");

fs.mkdirSync(path.join(ROOT, "db", "migrations"), { recursive: true });
fs.mkdirSync(path.join(ROOT, "model"), { recursive: true });
fs.mkdirSync(path.join(ROOT, "src", "generated"), { recursive: true });
fs.writeFileSync(path.join(ROOT, "db", "migrations", "0001_init.sql"), sql.join("\n") + "\n");
fs.writeFileSync(path.join(ROOT, "model", "entities.json"), JSON.stringify(model, null, 1));
fs.writeFileSync(path.join(ROOT, "src", "generated", "entities.ts"), "// Generated from Bullhorn metadata by crm/scripts/gen-schema.js — do not edit.\n" + ts.join("\n\n") + "\n\nexport type EntityName = " + ENTITIES.map(e => '"' + e + '"').join(" | ") + ";\n");
const nCols = Object.values(model).reduce((n, m) => n + m.fields.length, 0);
console.log("tables:", ENTITIES.length, "| fields:", nCols, "| join tables:", joins.length);
